!function(g){var E="//st-au.ants.vn/proxy-conversion.html",y,z,k,A,B,D,F={}.hasOwnProperty,G=[].slice,H=function(e,f){return function(){return e.apply(f,arguments)}};k={sha1:function(e){var f,a,c,d,b,n,w,p,t,l,m,q,k,h,s,r,u;s=function(a,b){return a<<b|a>>>32-b};k=function(a){var b,c;e="";for(b=7;0<=b;)c=a>>>4*b&15,e+=c.toString(16),b--;return e};f=h=q=void 0;m=[];n=1732584193;w=4023233417;p=2562383102;t=271733878;l=3285377520;a=r=b=d=c=a=f=void 0;u=[];e=unescape(g.encodeURIComponent(e));a=e.length;
for(h=0;h<a-3;)f=e.charCodeAt(h)<<24|e.charCodeAt(h+1)<<16|e.charCodeAt(h+2)<<8|e.charCodeAt(h+3),u.push(f),h+=4;switch(a&3){case 0:h=2147483648;break;case 1:h=e.charCodeAt(a-1)<<24|8388608;break;case 2:h=e.charCodeAt(a-2)<<24|e.charCodeAt(a-1)<<16|32768;break;case 3:h=e.charCodeAt(a-3)<<24|e.charCodeAt(a-2)<<16|e.charCodeAt(a-1)<<8|128}for(u.push(h);14!==(u.length&15);)u.push(0);u.push(a>>>29);u.push(a<<3&4294967295);for(q=0;q<u.length;){for(h=0;16>h;)m[h]=u[q+h],h++;for(h=16;79>=h;)m[h]=s(m[h-3]^
m[h-8]^m[h-14]^m[h-16],1),h++;f=n;a=w;c=p;d=t;b=l;for(h=0;19>=h;)r=s(f,5)+(a&c|~a&d)+b+m[h]+1518500249&4294967295,b=d,d=c,c=s(a,30),a=f,f=r,h++;for(h=20;39>=h;)r=s(f,5)+(a^c^d)+b+m[h]+1859775393&4294967295,b=d,d=c,c=s(a,30),a=f,f=r,h++;for(h=40;59>=h;)r=s(f,5)+(a&c|a&d|c&d)+b+m[h]+2400959708&4294967295,b=d,d=c,c=s(a,30),a=f,f=r,h++;for(h=60;79>=h;)r=s(f,5)+(a^c^d)+b+m[h]+3395469782&4294967295,b=d,d=c,c=s(a,30),a=f,f=r,h++;n=n+f&4294967295;w=w+a&4294967295;p=p+c&4294967295;t=t+d&4294967295;l=l+b&4294967295;
q+=16}r=k(n)+k(w)+k(p)+k(t)+k(l);return r.toLowerCase()},objectKeys:function(e){var f,a;a=[];for(f in e)F.call(e,f)&&a.push(f);return a},arrayEach:function(e,f){var a,c,d,b,n;if(null!=Array.prototype.forEach)return Array.prototype.forEach.call(e,f);n=[];a=d=0;for(b=e.length;d<b;a=++d)c=e[a],n.push(f.call(e,c,a,e));return n},isArray:function(e){return"[object Array]"===Object.prototype.toString.call(e)},each:function(e,f){var a;if(e){if(k.isArray(e))return k.arrayEach(e,f);a=this.objectKeys(e);return k.arrayEach(a,
function(a){return f.call(e,e[a],a,e)})}},map:function(e,f){var a;a=[];k.each(e,function(c,d){return a.push(f.call(e,c,d,e))});return a},filter:function(e,f){var a;a=[];k.each(e,function(c,d){if(f.call(e,c,d,e))return a.push(c)});return a},extend:function(){var e,f,a,c,d,b,n;c=arguments[0];a=2<=arguments.length?G.call(arguments,1):[];c=c||{};b=0;for(n=a.length;b<n;b++)for(e in f=a[b],f)d=f[e],c[e]=d;return c},nextTick:function(e){return k.delay(0,e)},delay:function(e,f){try{return setTimeout(f,e)}catch(a){}},
debounce:function(e,f){var a;a=null;return function(){var c,d;d=this;c=arguments_;clearTimeout(a);return a=setTimeout(function(){return e.apply(d,c)},f)}},json:function(e,f,a){var c,d;try{return"function"===typeof f&&(a=f,f={}),c=function(){var b;if(4===d.readyState&&200===d.status){b=d.responseText;try{return b=JSON.parse(b)}catch(c){}finally{a(b)}}},d=new XMLHttpRequest,d.open("GET",e,!0),d.withCredentials=!0===f.credentials,d.onreadystatechange=c,d.send()}catch(b){}},queue:function(e){var f,a,
c,d,b,n,g,p,k,l,m,q,v;m=[].slice;k=void 0;v=[];l=f=q=0;p=void 0;b=null;c=function(){};a=void 0;e||(e=Infinity);g=function(){for(var a,b,c;p=q<v.length&&f<e;)b=q++,c=v[b],a=m.call(c,1),a.push(d(b)),++f,c[0].apply(null,a)};d=function(a){return function(c,d){--f;null==b&&(null!=d?(b=d,q=l=NaN,n()):(v[a]=c,--l?p||g():n()))}};n=function(){null!=b?c(b):a?c(b,v):c.apply(null,[b].concat(v))};return k={defer:function(){b||(v.push(arguments),++l,g());return k},await:function(b){c=b;a=!1;l||n();return k},awaitAll:function(b){c=
b;a=!0;l||n();return k}}}};y=function(){function e(){this.syncInfo=H(this.syncInfo,this);var a,c,d=this;this.has=Object.prototype.hasOwnProperty;this.queueEvents=k.queue();this.isSyncInfo=!1;this.data={};this.queue=[];this.event=[];this.transactions={};this.locals={};this.locals.hostname=this.getDomain(g.location.href);this.locals.hostRerfer=this.getDomain(document.referrer);this.locals.isSameHost=this.locals.hostname===this.locals.hostRerfer;this.locals.refer=0;this.locals.internal=0;this.locals.utmSource=
{};this.instance=null;this.proxyStorage=new z;null!=(a=this.proxyStorage)&&null!=(c=a.iframe)&&(c.onload=function(){return d.syncInfo()})}var f;e.getInstance=function(){this.isSyncInfo||(this.instance=function(a,c,d){d.prototype=a.prototype;d=new d;a=a.apply(d,c);return Object(a)===a?a:d}(this,arguments,function(){}));return this.instance};e.prototype.setData=function(a){return this.data[a[1]]=a[2]||""};e.prototype.getData=function(a){return this.data[a]||""};e.prototype.syncInfo=function(a){var c,
d,b=this;null==a&&(a=function(){});d="ants_bc_"+this.locals.hostname.replace("www","");this.locals.timeBegin=(new Date).getTime();this.locals.pageView={conversion_id:"",products:[],page_type:"",time:0};if("undefined"===typeof c||null===c)c=0;this.queueEvents.defer(function(a){return b.proxyStorage.get("proxyDOMReady",a)});this.queueEvents.defer(function(a){return b.proxyStorage.get("au_aid",a)});this.queueEvents.defer(function(a){return b.proxyStorage.get(d,a)});this.queueEvents.defer(function(a){return b.proxyStorage.get("ad_product",
a)});this.queueEvents.defer(function(a){return b.proxyStorage.get("ad_vl",a)});return this.queueEvents.awaitAll(function(a,c){var d,e,f;b.locals.visitorId=c[1].value||"v";if(""===c[4].value||null==c[4].value)d="//au.ants.vn/get_loc?loc",b.locals.ip&&(d+="&ip-address="+b.locals.ip),k.json(d,function(a){var c;if(a.loc)return a=a.loc,b.locals.ip=a.ip,b.locals.area=JSON.stringify({zone:a.zone,province:a.province,country:a.country}),b.locals.province=a.province,null!=(c=b.proxyStorage)?c.set("ad_vl",a,
7776E6):void 0});e=c[2].value;b.locals.product=c[3].value;b.locals.sessionId=b.getLocalStorage("ants_ad_ss")||"";b.locals.utmSource=b.getDataUtmSource();null!=b.locals.utmSource.ants_clid&&(e=b.locals.utmSource.ants_clid);if(""===b.locals.sessionId||null==b.locals.sessionId||void 0===b.locals.sessionId||null!=e||!b.locals.isSameHost&&""!==document.referrer)b.locals.sessionId=b.getSessionId(),b.locals.refer=1,null!=e&&(b.locals.internal=1),b.setLocalStorage("ants_ad_ss",b.locals.sessionId,18E5),d=document.createElement("a"),
d.href=document.referrer.match(/(^[^#]*)/)[0];null!=e?(b.locals.bc=e,b.locals.bc_session=!0,b.setLocalStorage("ants_ad_bc",e,2592E6)):(b.locals.bc=b.getLocalStorage("ants_ad_bc"),b.locals.bc_session=!1);6>(null!=(f=String(b.locals.visitorId))?f.length:void 0)&&(b.locals.visitorId=b.getCookieStorage("au_aid"));if(""===b.locals.visitorId||null===b.locals.visitorId)return k.json("//au.ants.vn/get_id",{credentials:!0},function(a){var c,d,e;b.locals.visitorId=a.au_aid.toString();b.locals.gender=a.gender;
b.locals.visitorIdTimeCreate=a.au_gt;null!=(c=b.proxyStorage)&&c.set("au_aid",b.locals.visitorId,63072E6);b.setLocalStorage("au_aid",b.locals.visitorId,63072E6);null!=(d=b.proxyStorage)&&d.set("au_gt",b.locals.visitorIdTimeCreate,63072E6);null!=(e=b.proxyStorage)&&e.set("ad_vg",b.locals.gender,864E5);if(!b.isSyncInfo)return b.enqueue(),b.isSyncInfo=!0});if(!b.isSyncInfo)return b.enqueue(),b.isSyncInfo=!0})};e.prototype.getDomain=function(a){a=a.replace(/https?:\/\/(www.)?/i,"");return-1===a.indexOf("/")?
a:a.split("/")[0]};e.prototype.getFullTime=function(){var a,c,d,b,e,f;a=new Date;f=a.getFullYear();e=a.getMonth()+1;c=a.getDate();d=a.getHours();b=a.getMinutes();a=a.getSeconds();10>e.length&&(e="0"+e);10>c.length&&(c="0"+c);return f+"-"+e+"-"+c+" "+d+":"+b+":"+a};e.prototype.getDataUtmSource=function(){var a,c,d,b;a=g.location.href.match(/(^[^#]*)/)[0].split("?");a=a[a.length-1];d=a.split("&");a={};a.date_name=this.getFullTime();a.channel=this.getDomain(document.referrer);for(c=0;c<d.length;)b=d[c].split("="),
null!=b[0]&&null!=b[1]&&(-1<b[0].indexOf("utm_")||"ants_clid"===b[0])&&(a[b[0]]=b[1]),c++;a.referrer=document.referrer.match(/(^[^#]*)/)[0];a.url=g.location.href.match(/(^[^#]*)/)[0];return a};e.prototype.conversion=function(a){if("object"===typeof a&&(this.queue.push(a),this.isSyncInfo))return k.debounce(this.enqueue(),250)};e.prototype.push=function(a){if("object"===typeof a&&(this.queue.push(a),this.isSyncInfo))return k.debounce(this.enqueue(),250)};e.prototype.trackBeacon=function(){var a;a={siteId:"",
date:(new Date).getTime(),session:this.locals.sessionId,type:this.locals.typeConversion,bc:this.locals.bc,refer:this.locals.refer,internal:this.locals.internal,utm:encodeURI(JSON.stringify(this.locals.utmSource)),refUrl:encodeURIComponent(document.referrer.match(/(^[^#]*)/)[0]),url:encodeURIComponent(g.location.href.match(/(^[^#]*)/)[0])};return this.sendLog(f("//t.ants.vn/a1/rm/track-beacon",a))};e.prototype.enqueue=function(){var a,c,d,b,e,w,p,t,l,m,q,v,h,s,r,u,x=this;m=this.queue;null!=g.ants_delay_events&&
(m=m.concat(g.ants_delay_events));this.queue=[];g.ants_delay_events=[];if(0<m.length){e=[];p=!1;d=[];c=null;q=0;for(v=m.length;q<v;q++)b=m[q],null!=b.conversionId&&(a=b.customParams||[],d.push.apply(d,a),c=b.conversionId,a={conversion_id:b.conversionId,conversion_language:b.language||"en",conversion_format:b.format||"",conversion_currency:b.currency||"vnd",conversion_label:b.label||"",custom_params:b.custom_params||[],conversion_value:b.value||"",remarketing_only:b.remarketing_only||!1},e.push(a),""!==
this.locals.bc&&!1===a.remarketing_only&&""!==a.conversion_label&&(a.siteId=0,a.visitor=this.locals.visitorId||"v",a.date=(new Date).getTime(),a.bc=this.locals.bc,a.session=this.locals.sessionId,a.type=this.locals.typeConversion,a.refer=this.locals.refer,a.internal=this.locals.internal,a.utm=encodeURI(JSON.stringify(this.locals.utmSource)),a.refUrl=encodeURIComponent(document.referrer.match(/(^[^#]*)/)[0]),a.url=encodeURIComponent(g.location.href.match(/(^[^#]*)/)[0]),this.sendLog(f("//t.ants.vn/a1/rm/conversion-list",
a))));d=this.matchDynamicInfo(d,g.location.href.match(/(^[^#]*)/)[0]);l=null!=this.locals.product&&"object"===typeof this.locals.product?this.locals.product:{};try{for(t=Object.keys(l),w=0;w<(null!=t?t.length:void 0);)(null!=l?null!=(h=l[t[w]])?h.utime:void 0:void 0)<(new Date).getTime()-2592E6&&null!=l&&delete l[t[w]],w++}catch(C){}k.each(d,function(a){var b,d,e,f,n,g;"purchase"===a.ecomm_pagetype&&(p=!0);l[c]=null!=l[c]?l[c]:{};l[c].utime=(new Date).getTime();l[c][a.ecomm_pagetype]=null!=l[c][a.ecomm_pagetype]?
l[c][a.ecomm_pagetype]:[];d=l[c][a.ecomm_pagetype].length;b=null!=(e=l[c])?null!=(f=e[a.ecomm_pagetype])?f.indexOf(a.ecomm_prodid):void 0:void 0;-1!==b&&null!=(n=l[c])&&null!=(g=n[a.ecomm_pagetype])&&g.splice(b,1);l[c][a.ecomm_pagetype].push(a.ecomm_prodid);3<d&&l[c][a.ecomm_pagetype].splice(0,d-3);x.locals.pageView.conversion_id=c;x.locals.pageView.page_type=a.ecomm_pagetype;return x.locals.pageView.products.push({product:a.ecomm_prodid,quantity:a.ecomm_quantity})});null!=(s=this.proxyStorage)&&
s.set("ad_product",l);d={antspv:this.getPageview(),siteId:"",pgt:(null!=(r=this.locals)?null!=(u=r.pageView)?u.page_type:void 0:void 0)||"",conversion_id:c,events:encodeURI(JSON.stringify(e)),date:(new Date).getTime(),custom_params:d,session:this.locals.sessionId||"",bc:this.locals.bc,refer:this.locals.refer,internal:this.locals.internal,utm:encodeURI(JSON.stringify(this.locals.utmSource)),refUrl:encodeURIComponent(document.referrer.match(/(^[^#]*)/)[0]),url:encodeURIComponent(g.location.href.match(/(^[^#]*)/)[0])};
this.sendLog(f("//t.ants.vn/a1/rm/matching-remarketing",d));p&&this.sendLog(f("//t.ants.vn/a1/rm/conversion-list",d));"v"!==this.locals.visitorId&&this.getUserMarketingList(f("//d.ants.vn/delivery/remarketing-list",d));return this.getScriptsFromConversion("//d.ants.vn/conversion-script",c)}};e.prototype.getPageview=function(){if(null!=("undefined"!==typeof g&&null!==g?g._antspv:void 0))return"undefined"!==typeof g&&null!==g?g._antspv:void 0;"undefined"!==typeof g&&null!==g&&(g._antspv=(new Date).getTime());
return"undefined"!==typeof g&&null!==g?g._antspv:void 0};e.prototype.matchDynamicInfo=function(a,c){var d,b,e,f,p,t,l,m,q,v,h,s,r,u,x,C,y,z,A;try{return f=document.domain.replace("www.",""),"lazada.vn"===f&&(p=(null!=(l=document.getElementById("pdtsku"))?l.innerHTML:void 0)||("undefined"!==typeof b&&null!==b?b.pdt_simplesku:void 0),t=RegExp("<[^>]*>","g"),t.test(p)&&(p=p.replace(t,"")),b=null!=(null!=(m=dataLayer[0])?m.pdt_simplesku:void 0)?dataLayer[0]:dataLayer[1],null!=(null!=b?b.pdt_simplesku:
void 0)&&a.push({ecomm_name:((null!=b?b.pdt_name:void 0)||"").replace(/&/g,"-").toLowerCase(),ecomm_brand:((null!=b?b.brand:void 0)||"").replace(/&/g,"-"),ecomm_cate:((null!=b?b.sub_subcategory:void 0)||(null!=b?b.subcategory:void 0)||(null!=b?b.category:void 0)||"").replace(/&/g,"-"),ecomm_prodid:p,ecomm_pagetype:"product",ecomm_quantity:1,ecomm_totalvalue:null!=b?b.pdt_price:void 0}),d=null!=(null!=(s=dataLayer[0])?null!=(r=s.ecommerce)?r.cart:void 0:void 0)?dataLayer[0]:dataLayer[1],null!=(null!=
d?null!=(u=d.ecommerce)?u.cart:void 0:void 0)&&-1!==g.location.href.indexOf("lazada.vn/cart/tracking")&&k.each(null!=(x=d.ecommerce)?x.cart:void 0,function(b){return a.push({ecomm_prodid:b.sku,ecomm_pagetype:"cart",ecomm_quantity:b.quantity,ecomm_totalvalue:b.price*b.quantity})}),e=null!=(null!=(C=dataLayer[0])?C.order_items:void 0)?dataLayer[0]:dataLayer[1],null!=(null!=e?e.order_items:void 0)&&k.each(e.order_items,function(b){return a.push({ecomm_prodid:b.id,ecomm_pagetype:"purchase",ecomm_quantity:b.quantity,
ecomm_totalvalue:b.price*b.quantity,ecomm_order_id:"order_id:"+e.order_id+" - order_number:"+e.order_number})})),"deca.vn"===f&&("offerdetail"===(null!=(y=dataLayer[0])?y.dynx_pagetype:void 0)&&a.push({ecomm_prodid:null!=(z=dataLayer[0])?z.productid:void 0,ecomm_pagetype:"product",ecomm_quantity:1,ecomm_totalvalue:null!=(A=dataLayer[0])?A.dynx_totalvalue:void 0}),"conversionintent"===(null!=(q=dataLayer[0])?q.dynx_pagetype:void 0)&&k.each(dataLayer[0].dynx_itemid,function(b,c){var d,e,f;d=null!=(e=
dataLayer[0].prices)?e.toString().split("|"):void 0;e=null!=(f=dataLayer[0].quantities)?f.toString().split("|"):void 0;return a.push({ecomm_prodid:b,ecomm_pagetype:"cart",ecomm_quantity:e[c],ecomm_totalvalue:d[c]*e[c]})}),"conversion"===(null!=(v=dataLayer[0])?v.dynx_pagetype:void 0)&&k.each(null!=(h=dataLayer[0].productid)?h.split("|"):void 0,function(b,c){var d;d=dataLayer[0].transactionProducts[c];return a.push({ecomm_prodid:b,ecomm_pagetype:"purchase",ecomm_quantity:d.quantity,ecomm_totalvalue:d.price*
d.quantity,ecomm_order_id:"order_id:"+dataLayer[0].orderid})})),a}catch(B){return[]}};e.prototype.matchUserMarketingList=function(a){return k.json(a,function(a){})};e.prototype.getUserMarketingList=function(a){var c;return null!=(c=this.proxyStorage)?c.set("ad_rmu",(new Date).getTime()):void 0};e.prototype.getScriptsFromConversion=function(a,c){var d=this;return k.json(""+a+"?conversion_id="+c,function(a){var c,e;if(0<(null!=a?null!=(e=a.scripts)?e.length:void 0:void 0))return c=document.createElement("div"),
c.className="script-ants-append",c.style.display="none",document.body.appendChild(c),null!=a?a.scripts.forEach(function(a){return d.appendScript(c,a)}):void 0})};e.prototype.appendScript=function(a,c){var d,b;b=document.createElement("span");b.className="span-append";b.style.display="none";a.appendChild(b);d=document.createElement("script");null!=(null!=c?c.text:void 0)?d.text=c.text:(d.src=c.src,d.async=1);return b.parentNode.replaceChild(d,b)};f=function(a,c){var d,b,e,f;d=-1<a.indexOf("?");e=[];
for(b in c){f=c[b];try{"string"!==typeof f&&(f=JSON.stringify(f)),e.push(""+b+"="+f)}catch(g){}}return a+(d?"&":"?")+e.join("&")};e.prototype.sendLog=function(a,c){var d;null==c&&(c=function(){});d=new Image(1,1);d.onload=c;return d.src=a};e.prototype.globalize=function(a){var c,d;d=[];for(c in a)a.hasOwnProperty(c)?d.push(g[c]=a[c]):d.push(void 0);return d};e.prototype.getSessionId=function(){var a;a=1E3*new Date+~~(1E3*Math.random());return k.sha1(this.locals.visitorId+a+g.location.href)};e.prototype.setLocalStorage=
function(a,c,d){var b;try{return null!=(b=this.cookie)?b.setItem(a,c,d):void 0}catch(e){}};e.prototype.removeLocalStorage=function(a){var c;try{null!=(c=this.cookie)&&c.removeItem(a)}catch(d){}return ex};e.prototype.getLocalStorage=function(a){var c;try{return null!=(c=this.cookie)?c.getItem(a):void 0}catch(d){}};e.prototype.getCookieStorage=function(a){var c,d,b;try{return c=null!=(d=this.cookie)?d.getItem(a):void 0,6>(null!=(b=String(c))?b.length:void 0)?this.storage.getItem(a):c}catch(e){}};e.prototype.cookie=
{getItem:function(a){return a&&this.hasItem(a)?unescape(document.cookie.replace(RegExp("(?:^|.*;\\s*)"+escape(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*((?:[^;](?!;))*[^;]?).*"),"$1")):null},setItem:function(a,c,d,b,e,f){var g;b="/";e="."+document.domain.replace("www.","");if(a&&!/^(?:expires|max\-age|path|domain|secure)$/.test(a)){g="";if(d)switch(typeof d){case "number":g="; max-age="+d/1E3;break;case "string":g="; expires="+d;break;case "object":d.hasOwnProperty("toGMTString")&&(g="; expires="+
d.toGMTString())}return document.cookie=escape(a)+"="+escape(c)+g+(e?"; domain="+e:"")+(b?"; path="+b:"")+(f?"; secure":"")}},removeItem:function(a){var c;a&&this.hasItem(a)&&(c=new Date,c.setDate(c.getDate()-1),document.cookie=escape(a)+"=; expires="+c.toGMTString()+"; path=/")},hasItem:function(a){return RegExp("(?:^|;\\s*)"+escape(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=").test(document.cookie)}};e.prototype.storage={getItem:function(a){var c,d,b,e;c={};try{e=JSON.parse(g.localStorage.getItem(a))}catch(f){}d=
g.localStorage.getItem("expire-"+a);b=null===d?!1:Number(d)<Date.now();if(""===e||null===e)e=JSON.parse(g.localStorage.getItem(a));null==e||b||(c.value=e);c.expire=d||0;return c},setItem:function(a,c,d){var b,e,f;try{return null!=(b=g.localStorage)&&b.setItem(a,JSON.stringify(c)),null===d||isNaN(d)?null!=(e=g.localStorage)?e.removeItem("expire-"+a):void 0:null!=(f=g.localStorage)?f.setItem("expire-"+a,Date.now()+d):void 0}catch(k){}},removeItem:function(a){var c;c="expire-"+a;g.localStorage.removeItem(a);
return g.localStorage.removeItem(c)},removeExpiredKey:function(a){var c,d,b,e;b=g.localStorage;e=[];for(d in b)c=b[d],/expire\-/.test(d)&&(a>Number(c)?(c=d.substr(7),storage.removeItem(d),e.push(storage.removeItem(c))):e.push(void 0));return e}};return e}();z=function(){function e(){var a;this.$counter=0;this.$callbacks={};this.isSupported()&&(a=this.iframe=document.createElement("iframe"),a.src=E,a.width=0,a.height=0,a.style.display="none",this.append(),this.proxyWin=a.contentWindow)}var f;f=g.postMessage&&
g.JSON;e.prototype.isSupported=function(){return f};e.prototype.addEventListener=function(a,c,d){a=a===g?g:a[0]||a;return a.addEventListener?(a.addEventListener(c,d,!1),!0):a.attachEvent?a.attachEvent("on"+c,d):!1};e.prototype.onMessage=function(a){return this.addEventListener(g,"message",function(c){var d;try{d=JSON.parse(c.data)}catch(b){d=null}return a(d)})};e.prototype.append=function(){var a,c;if(!this.isSupported())return!1;a=this.iframe;c=this;document.getElementsByTagName("head")[0].appendChild(a);
this.onMessage(function(a){if(a&&"ants-proxy-conversion"===a.$)return c.receiver(a)});return!0};e.prototype.receiver=function(a){var c,d;"proxyDOMReady"===a.event&&(this.instance=!0);d=a.$id;c=this.$callbacks[d];if(d&&c)return k.nextTick(function(){return c(a)}),delete this.$callbacks[d]};e.prototype.send=function(a){a.$="ants-proxy-conversion";return this.proxyWin.postMessage(JSON.stringify(a),"*")};e.prototype.set=function(a,c,d,b){var e;"function"===typeof d&&(b=d,d=null);e={key:a,value:c,expire:d};
if(this.isSupported())return e.action="set",e.$id=++this.$counter,this.$callbacks[e.$id]=b,this.send(e);k.nextTick(function(){return"function"===typeof b?b(e):void 0})};e.prototype.get=function(a,c){var d;if(!this.isSupported())return c({error:"not supported"});d={key:a};if(this.isSupported())return d.action="get",d.$id=++this.$counter,this.$callbacks[d.$id]=c,this.send(d);k.nextTick(function(){return"function"===typeof c?c(d):void 0})};return e}();null!=(null!=(A=g.ants_analytic)?null!=(B=A[0])?B.conversionId:
void 0:void 0)&&(g.ants_delay_events=g.ants_analytic);void 0===(null!=(D=g.ants_analytic)?D.isSyncInfo:void 0)&&(g.ants_analytic=y.getInstance())}(window);
